# Supabase Authentication Configuration
# Security-hardened settings

[auth]
# JWT Configuration
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080/**"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_email_change_enabled = true
# Reduce OTP expiry time for security (5 minutes instead of default 60)
otp_expiry = 300

[auth.email.template.invite]
subject = "You have been invited to StudyFlow AI"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm your email for StudyFlow AI"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your password for StudyFlow AI"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.email_change]
subject = "Confirm your email change for StudyFlow AI"
content_path = "./supabase/templates/email_change.html"

[auth.sms]
enable_signup = false
enable_confirmations = false
# SMS OTP expiry (2 minutes for higher security)
otp_expiry = 120
max_frequency = 5
test_otp = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.password]
# Strong password requirements
min_length = 12
# Enable leaked password protection (HaveIBeenPwned API)
leaked_password_protection = true
# Require at least one uppercase, lowercase, number, and special character
required_characters = "uppercase,lowercase,numbers,symbols"

[auth.mfa]
# Enable MFA for enhanced security
enabled = true
# Maximum number of enrolled factors per user
max_enrolled_factors = 5
# Verification code expiry (5 minutes)
factor_expiry = 300

[auth.sessions]
# Session configuration
inactivity_timeout = 86400  # 24 hours
# Lifetime timeout (7 days)
lifetime_timeout = 604800
# Enable session refresh
refresh_enabled = true
# Refresh token rotation
refresh_token_rotation_enabled = true

[auth.security]
# Security settings
refresh_token_reuse_interval = 10
# Enable CAPTCHA for signup/signin
captcha_enabled = false
captcha_provider = "hcaptcha"  # or "turnstile" for Cloudflare
captcha_secret = ""

# Rate limiting
[auth.rate_limits]
# Email rate limits
email_hourly_rate_limit = 5
email_daily_rate_limit = 20
# SMS rate limits
sms_hourly_rate_limit = 3
sms_daily_rate_limit = 10
# Password reset rate limits
password_reset_hourly_rate_limit = 3
password_reset_daily_rate_limit = 5
# Signup rate limits
signup_hourly_rate_limit = 10
signup_daily_rate_limit = 50

# Additional security headers
[auth.security_headers]
hsts_max_age = 63072000  # 2 years
hsts_include_subdomains = true
hsts_preload = true
x_frame_options = "DENY"
x_content_type_options = "nosniff"
x_xss_protection = "1; mode=block"
referrer_policy = "strict-origin-when-cross-origin"

# Webhook configuration for security events
[auth.webhook]
enabled = false
url = ""
secret = ""
events = ["signup", "login", "logout", "user.updated", "user.deleted", "password.recovery", "mfa.enroll", "mfa.challenge", "mfa.verify"]

# IP-based restrictions
[auth.ip_restrictions]
# Allow list (if empty, all IPs are allowed)
allow_list = []
# Deny list (blocked IPs)
deny_list = []

# Account lockout policy
[auth.lockout]
enabled = true
# Lock account after N failed attempts
max_attempts = 5
# Lockout duration in seconds (30 minutes)
lockout_duration = 1800
# Reset failed attempts after successful login
reset_on_success = true