# Supabase Project Configuration
project_id = "uuebhjidsaswvuexdcbb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080"]

[studio]
enabled = true
port = 54323

[functions.deepseek-ai-professional]
verify_jwt = false

[functions.deepseek-quote]
verify_jwt = false

[functions.deepseek-chat]
verify_jwt = false
